name: call_run-this
on: workflow_dispatch
jobs:
  call-workflow-passing-data:
    uses: AllStarLink/asl_workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: docker run --privileged --platform linux/arm -it arm32v7/debian uname -a
      arch: arm64
      artifact-path: /var/log/cloud*
    secrets: inherit
